"""empty message

Revision ID: 210ad4a0c6c7
Revises: 3cd827741450
Create Date: 2015-05-26 03:48:54.150050

"""

# revision identifiers, used by Alembic.
revision = '210ad4a0c6c7'
down_revision = '3cd827741450'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    ### end Alembic commands ###
