"""empty message

Revision ID: 3cd827741450
Revises: 160ab0514e15
Create Date: 2015-05-26 03:23:57.260499

"""

# revision identifiers, used by Alembic.
revision = '3cd827741450'
down_revision = '160ab0514e15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
